import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    scrollContent: {
        paddingBottom: 12,
    },
    pagePadding: {
        paddingHorizontal: 12,
        paddingTop: 12,
    },
    saveButton: {
        minWidth: 60,
        height: 34,
        borderRadius: 9,
        backgroundColor: '#0A6B63',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 14,
    },
    saveButtonDisabled: {
        backgroundColor: '#7AA8A3',
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        lineHeight: 18,
        fontWeight: '800',
    },
    sectionCard: {
        backgroundColor: '#FFF',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#D7DCE3',
        overflow: 'hidden',
        marginBottom: 18,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#D7DCE3',
    },
    sectionHeaderCopy: {
        marginLeft: 10,
        flex: 1,
    },
    sectionTitle: {
        color: '#2A3140',
        fontSize: 16,
        lineHeight: 22,
        fontWeight: '800',
    },
    sectionSubtitle: {
        color: '#6B7280',
        fontSize: 14,
        lineHeight: 20,
        marginTop: 2,
    },
    sectionBody: {
        padding: 12,
    },
    profilePhotoBlock: {
        textAlign: 'center',
        alignItems: 'center',
        marginBottom: 14,
    },
    profileMonogram: {
        width: 62,
        height: 62,
        borderRadius: 31,
        backgroundColor: '#0A6B63',
        alignItems: 'center',
        justifyContent: 'center',
    },
    profileMonogramText: {
        color: '#FFFFFF',
        fontSize: 22,
        lineHeight: 26,
        fontWeight: '800',
    },
    profileSyncText: {
        color: '#6B7280',
        fontSize: 13,
        lineHeight: 18,
        marginTop: -4,
        marginBottom: 8,
    },
    fieldWrap: {
        marginBottom: 14,
    },
    inputShellWrap: {
        position: 'relative',
        justifyContent: 'center',
    },
    fieldLabel: {
        color: '#5B6575',
        fontSize: 14,
        lineHeight: 20,
        fontWeight: '700',
        marginBottom: 6,
    },
    inputShell: {
        minHeight: 44,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#D1D5DB',
        backgroundColor: '#FFF',
        paddingHorizontal: 12,
        color: '#1F2937',
        fontSize: 15,
    },
    inputShellWithAccessory: {
        paddingRight: 44,
    },
    inputAccessory: {
        position: 'absolute',
        right: 12,
        top: 0,
        bottom: 0,
        alignItems: 'center',
        justifyContent: 'center',
    },
    inputShellMultiline: {
        minHeight: 84,
        paddingTop: 12,
        textAlignVertical: 'top',
    },
    securityRow: {
        backgroundColor: '#F9FAFB',
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    securityCopy: {
        flex: 1,
        paddingRight: 12,
    },
    securityTitle: {
        color: '#374151',
        fontSize: 16,
        lineHeight: 20,
        fontWeight: '700',
    },
    securitySubtitle: {
        color: '#6B7280',
        fontSize: 14,
        lineHeight: 19,
        marginTop: 2,
    },
    securityActionButton: {
        paddingVertical: 4,
    },
    securityActionButtonPrimary: {
        minWidth: 58,
        height: 34,
        borderRadius: 8,
        backgroundColor: '#0A6B63',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 14,
    },
    securityActionText: {
        fontSize: 14,
        lineHeight: 18,
        fontWeight: '700',
    },
    securityActionTextDefault: {
        color: '#0A6B63',
    },
    securityActionTextPrimary: {
        color: '#FFFFFF',
    },
    statusBadge: {
        minWidth: 56,
        height: 32,
        borderRadius: 999,
        backgroundColor: '#DDF5E2',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 12,
    },
    statusBadgeText: {
        color: '#55A869',
        fontSize: 14,
        lineHeight: 18,
        fontWeight: '700',
    },
    signOutButton: {
        height: 54,
        borderRadius: 12,
        backgroundColor: '#F8E9E9',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        marginBottom: 4,
    },
    passwordButton: {
        height: 46,
        borderRadius: 10,
        backgroundColor: '#0A6B63',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 2,
    },
    passwordButtonDisabled: {
        backgroundColor: '#7AA8A3',
    },
    passwordButtonText: {
        color: '#FFFFFF',
        fontSize: 15,
        lineHeight: 20,
        fontWeight: '800',
    },
    passwordCancelButton: {
        alignSelf: 'center',
        paddingHorizontal: 10,
        paddingVertical: 8,
        marginTop: 4,
    },
    passwordCancelButtonText: {
        color: '#0A6B63',
        fontSize: 14,
        lineHeight: 18,
        fontWeight: '700',
    },
    passwordFormBlock: {
        marginTop: 2,
    },
    signOutText: {
        color: '#EF4444',
        fontSize: 16,
        lineHeight: 20,
        fontWeight: '800',
        marginLeft: 8,
    },
});

export { styles };
export default styles;
